### ISSUE TITLE
Issue with running docker

### ISSUE THREAD

**Issue by Kathir-66** [GrotjahnLab/surface_morphometrics#33]
I tried using the docker. I was successfully able to activate the docker but when I try to run segmentation_to_meshes.py, I got the error ImportError: libGL.so.1: cannot open shared object file: No such file or directory  

```
(base) kaezhila@kraken  ~/Programs/surface_morphometrics/docker $ > ./sm-up.sh 
Starting container...
WARN[0000] /home/kaezhila/Programs/surface_morphometrics/docker/docker-compose.yml: `version` is obsolete 
[+] Running 13/13
 ✔ surface_morphometrics Pulled                                                                                                                                                                                                  45.5s 
   ✔ a480a496ba95 Pull complete                                                                                                                                                                                                   1.9s 
   ✔ 10c7b90e2b4b Pull complete                                                                                                                                                                                                   3.5s 
   ✔ 46939b65c12f Pull complete                                                                                                                                                                                                   7.1s 
   ✔ 1d08c40ec593 Pull complete                                                                                                                                                                                                   9.1s 
   ✔ 981106d742a2 Pull complete                                                                                                                                                                                                   9.2s 
   ✔ 64087a344656 Pull complete                                                                                                                                                                                                   9.2s 
   ✔ 606732e8ed8d Pull complete                                                                                                                                                                                                  34.2s 
   ✔ 77cdf953e75e Pull complete                                                                                                                                                                                                  34.8s 
   ✔ 546ccfcc0747 Pull complete                                                                                                                                                                                                  35.2s 
   ✔ 6bc68b0c9093 Pull complete                                                                                                                                                                                                  35.8s 
   ✔ 815a481313cc Pull complete                                                                                                                                                                                                  43.7s 
   ✔ 12256ecd13a7 Pull complete                                                                                                                                                                                                  43.9s 
[+] Running 2/2
 ✔ Network docker_default                     Created                                                                                                                                                                             0.1s 
 ✔ Container surface_morphometrics_container  Started                                                                                                                                                                             5.5s 
Waiting for container...
WARN[0000] /home/kaezhila/Programs/surface_morphometrics/docker/docker-compose.yml: `version` is obsolete 
Entering container...
```

```

(morphometrics) root@006a8c3cc05d:/surface_morphometrics# python segmentation_to_meshes.py config.yml 
Traceback (most recent call last):
  File "segmentation_to_meshes.py", line 24, in <module>
    import xyz2ply
  File "/surface_morphometrics/xyz2ply.py", line 13, in <module>
    import pymeshlab as pm
  File "/opt/conda/envs/morphometrics/lib/python3.7/site-packages/pymeshlab/__init__.py", line 11, in <module>
    from .pmeshlab import *
ImportError: libGL.so.1: cannot open shared object file: No such file or directory

```

**Comment by bbarad** [comment]
not sure how we ended up without a complete pymeshlab install - @hemanthkapa assigning this to you for now.

**Comment by hemanthkapa** [comment]
New commit should work. 😁

**Comment by bbarad** [comment]
Just merged Hemanth's PR for this - looks like it will address this issue. Thanks for testing!

**Comment by Kathir-66** [comment]
This is working, Thank you very much!
